mode: increment
blade-directive: version
current:
  label: v
  major: 1
  minor: 0
  patch: 0
  prerelease:
  buildmetadata:
  commit:
  revision:
  timestamp: { mode: absorb, year: null, month: null, day: null, hour: null, minute: null, second: null, timezone: null }
format:
  regex:
    optional_bracket: '\[(?P<prefix>.*?)(?P<spaces>\s*)(?P<delimiter>\?\=)(?P<optional>.*?)\]'
  label: "{$label}"
  major: "{$major}"
  minor: "{$minor}"
  patch: "{$patch}"
  prerelease: "{$prerelease}"
  buildmetadata: "{$buildmetadata}"
  commit: "{$commit}"
  version: 'version {$major}.{$minor}.{$patch} (commit {$commit})'
  version-only: 'version {$major}.{$minor}.{$patch}'
  ## Bracket enclosed expressions "[.?{$variable}]" are only rendered if the ?={$variable} is filled
  full: '{$version-only}[.?={$prerelease}][+?={$buildmetadata}] (commit {$commit})'
  compact: "{$label}{$major}.{$minor}.{$patch}-{$commit}"
  tag: "{$label}{$major}.{$minor}.{$patch}"
  timestamp-year: '{$timestamp.year}'
  timestamp-month: '{$timestamp.month}'
  timestamp-day: '{$timestamp.day}'
  timestamp-hour: '{$timestamp.hour}'
  timestamp-minute: '{$timestamp.minute}'
  timestamp-second: '{$timestamp.second}'
  timestamp-timezone: '{$timestamp.timezone}'
  timestamp-datetime: '{$timestamp.year}-{$timestamp.month}-{$timestamp.day} {$timestamp.hour}:{$timestamp.minute}:{$timestamp.second}'
  timestamp-full: '{$timestamp.year}-{$timestamp.month}-{$timestamp.day} {$timestamp.hour}:{$timestamp.minute}:{$timestamp.second} {$timestamp.timezone}'
  ## add as many formats as you need !!!!
tag-format: tag
